/* Generated by .verify/build-embed.mjs. Do not edit by hand. */
window.EMBEDDED_TRACES = {
 "ch1": {
  "id": "ch1",
  "title": "One model call",
  "code": "one_call",
  "world": {
   "scene": "none"
  },
  "intro": "A model call is one request to the API. You send a list of messages and receive one message back.",
  "steps": [
   {
    "node": "think",
    "author": "system",
    "label": "System",
    "text": "You are a helpful assistant.",
    "codeLine": 5,
    "narration": "People call this the prompt. It is a list of messages. The first item is the system message: instructions for this call."
   },
   {
    "node": "think",
    "author": "user",
    "label": "User",
    "text": "What is 2 + 2?",
    "codeLine": 6,
    "narration": "The second item is the user message, the question you want answered. The list now has two messages."
   },
   {
    "node": "think",
    "author": "model",
    "label": "Assistant",
    "text": "4",
    "codeLine": 9,
    "narration": "Your program calls OpenAI's Chat Completions API with chat.completions.create, passing the message list and the model gpt-4.1-mini. The API returns one response object that contains an assistant message. print outputs that message's text. The program does not call the model again.",
    "note": {
     "text": "Many models and inference providers accept this same Chat Completions request. Learn more in the",
     "href": "https://platform.openai.com/docs/api-reference/chat/create",
     "link": "Chat Completions API docs"
    }
   }
  ]
 },
 "ch2": {
  "id": "ch2",
  "title": "One tool call",
  "code": "one_tool",
  "world": {
   "scene": "single_tool",
   "status": "ready",
   "input": null,
   "result": null
  },
  "intro": "The model can return a tool call instead of text: the name of a function and its arguments. Your program runs that function once. It does not call the model again.",
  "steps": [
   {
    "node": "think",
    "author": "system",
    "label": "System",
    "text": "Use the weather tool.",
    "codeLine": 15,
    "narration": "The system message tells the model to use the weather tool. The tool schema, sent with the request, names get_weather and its city argument."
   },
   {
    "node": "think",
    "author": "user",
    "label": "User",
    "text": "Weather in Paris?",
    "codeLine": 16,
    "narration": "The user asks for weather in Paris. One chat.completions.create sends the messages and the tool schema together."
   },
   {
    "node": "act",
    "author": "model",
    "label": "Tool call",
    "text": "get_weather {\"city\": \"Paris\"}",
    "codeLine": 21,
    "set": {
     "status": "requested",
     "input": {
      "city": "Paris"
     }
    },
    "narration": "The model does not fetch weather. It returns a tool call: the name get_weather and the argument city=Paris. Your code has not run yet."
   },
   {
    "node": "none",
    "author": "tool",
    "label": "Tool result",
    "text": "{\"city\": \"Paris\", \"temp_c\": 18, \"sky\": \"rain\"}",
    "codeLine": 23,
    "set": {
     "status": "done",
     "result": {
      "city": "Paris",
      "temp_c": 18,
      "sky": "rain"
     }
    },
    "narration": "Your program runs get_weather(city=\"Paris\") and prints the dict it returned. There is no second model call, so the model never sees this result."
   }
  ]
 },
 "ch3": {
  "id": "ch3",
  "title": "Working memory",
  "code": "context",
  "world": {
   "scene": "meter",
   "used": 0,
   "max": 200000
  },
  "intro": "The model has no other memory. It only sees the messages you send on this call. That list is working memory, and it grows with every tool result you append.",
  "steps": [
   {
    "node": "think",
    "author": "system",
    "label": "System",
    "tokens": 3100,
    "text": "You are a coding agent. Tools: read_file, edit_file, run_command.",
    "codeLine": 22,
    "set": {
     "used": 3100
    },
    "narration": "Working memory starts as this messages list. The system message is about 3,100 tokens. The next call will send it again."
   },
   {
    "node": "think",
    "author": "user",
    "label": "User",
    "tokens": 12,
    "text": "Refactor the parser and make the tests pass.",
    "codeLine": 25,
    "set": {
     "used": 3112
    },
    "narration": "The user message is the second item. print(len(messages)) reports 2. That is the whole list so far."
   },
   {
    "node": "observe",
    "author": "tool",
    "label": "Tool result",
    "tokens": 18400,
    "text": "parser.py (812 lines)",
    "codeLine": 26,
    "set": {
     "used": 21512
    },
    "narration": "Your program appends the file contents as a tool result. The list is now 3. The next call sends the whole list, including this file."
   },
   {
    "node": "observe",
    "author": "tool",
    "label": "Tool result",
    "tokens": 9600,
    "text": "pytest: 14 failed, 2 passed",
    "codeLine": 27,
    "set": {
     "used": 31112
    },
    "narration": "Test output is appended too. The list is now 4. The model can use it only while it remains in the list."
   },
   {
    "node": "observe",
    "author": "tool",
    "label": "Tool result",
    "tokens": 19000,
    "text": "Updated parser.py (840 lines)",
    "codeLine": 28,
    "set": {
     "used": 50112
    },
    "narration": "Reading the file again appends a second copy. Your program decides what stays. The model cannot drop messages on its own."
   },
   {
    "node": "observe",
    "author": "tool",
    "label": "Tool result",
    "tokens": 118000,
    "text": "Additional file contents and test output",
    "codeLine": 30,
    "set": {
     "used": 168112
    },
    "narration": "print(len(messages)) is now 6. estimate_tokens reads 168,112. Each model has a context window: a hard limit on how many tokens it can read."
   },
   {
    "node": "think",
    "author": "system",
    "label": "Summary",
    "tokens": 9800,
    "collapse": true,
    "text": "Summary: refactoring parser.py. 11 of 14 tests pass. Remaining: CSV quoting, trailing newline, Unicode escape.",
    "codeLine": 31,
    "set": {
     "used": 9800
    },
    "narration": "The estimate is over TOKEN_LIMIT. summarize_if_needed keeps the system prompt and original task, and replaces the rest with one summary. That shorter list is now working memory."
   }
  ]
 },
 "ch6": {
  "id": "ch6",
  "title": "Choose the next message",
  "code": "choose",
  "world": {
   "scene": "files",
   "files": [
    {
     "name": "app.py",
     "status": ""
    },
    {
     "name": "config.yaml",
     "status": ""
    }
   ],
   "term": []
  },
  "intro": "You play the model. You pick the next assistant message. The program still runs any tool you request and appends the result to the list.",
  "steps": [
   {
    "node": "think",
    "author": "system",
    "label": "System",
    "text": "You are a coding agent. Tools: read_file, edit_file, run_command. Read files before answering about their contents.",
    "codeLine": 27,
    "narration": "The system message tells the model to read files before answering. The program has already attached three tools: read_file, edit_file, and run_command."
   },
   {
    "node": "think",
    "author": "user",
    "label": "User",
    "text": "What does config.yaml set?",
    "codeLine": 31,
    "narration": "The user asks what config.yaml sets. The filename is in the list. The file contents are not."
   },
   {
    "node": "act",
    "author": "model",
    "label": "Tool call",
    "text": "read_file {\"path\": \"config.yaml\"}",
    "codeLine": 7,
    "prompt": "Pick the model's next message.",
    "choices": [
     {
      "text": "read_file {\"path\": \"config.yaml\"}",
      "correct": true
     },
     {
      "text": "config.yaml sets debug: true.",
      "deadend": "The file contents are not in the messages, so that answer is a guess. Read the file first."
     },
     {
      "text": "edit_file {\"path\": \"config.yaml\", \"old\": \"false\", \"new\": \"true\"}",
      "deadend": "That would change the file. The question asked what it sets. Read it first."
     }
    ],
    "set": {
     "files": [
      {
       "name": "app.py",
       "status": ""
      },
      {
       "name": "config.yaml",
       "status": "read"
      }
     ]
    },
    "add": {
     "term": [
      "$ read_file config.yaml"
     ]
    },
    "narration": "You requested read_file. That is a function in this program. The program runs it. You do not read the disk yourself."
   },
   {
    "node": "observe",
    "author": "tool",
    "label": "Tool result",
    "text": "debug: false\nport: 8080",
    "codeLine": 8,
    "add": {
     "term": [
      "2 lines"
     ]
    },
    "narration": "read_file returns the file text. That string is appended to the list. The next message can answer from those values."
   },
   {
    "node": "think",
    "author": "model",
    "label": "Assistant",
    "text": "config.yaml sets debug: false and port: 8080.",
    "codeLine": 30,
    "prompt": "Pick what the model returns.",
    "choices": [
     {
      "text": "config.yaml sets debug: false and port: 8080.",
      "correct": true
     },
     {
      "text": "read_file {\"path\": \"app.py\"}",
      "deadend": "The list already has the answer. Reading app.py would only add more tokens."
     }
    ],
    "narration": "That choice is the assistant message. It has no tool call, so the loop stops and run_agent returns this text."
   },
   {
    "node": "none",
    "author": "system",
    "label": "Note",
    "text": "You read the file, then answered from its contents.",
    "codeLine": 16,
    "narration": "You chose the messages. The program ran the tools in TOOLS and wrote the observations. That split is the agent."
   }
  ]
 },
 "ch7": {
  "id": "ch7",
  "title": "Memory between runs",
  "code": "saved_memory",
  "world": {
   "scene": "memory",
   "session": 1,
   "records": [],
   "query": null
  },
  "intro": "A new run starts with a new messages list. Anything only stored in the old list is gone. To keep a fact across runs, your program writes it outside the list, here to a SQLite file.",
  "steps": [
   {
    "node": "think",
    "author": "system",
    "label": "System",
    "text": "Use short snake_case keys, like editor. remember(key, value) and recall(key).",
    "codeLine": 25,
    "narration": "The system message names the key convention. Both runs see the same instruction, so remember and recall can use the same key."
   },
   {
    "node": "think",
    "author": "user",
    "label": "User",
    "text": "Remember that my editor is Helix.",
    "codeLine": 29,
    "narration": "The user asks to store a preference. That sentence lives only in this run's messages until a tool writes it out."
   },
   {
    "node": "act",
    "author": "model",
    "label": "Tool call",
    "text": "remember {\"key\": \"editor\", \"value\": \"Helix\"}",
    "codeLine": 8,
    "narration": "The model returns a remember tool call with key editor and value Helix. It cannot write the database itself."
   },
   {
    "node": "observe",
    "author": "tool",
    "label": "Tool result",
    "text": "Stored editor = Helix",
    "codeLine": 10,
    "add": {
     "records": [
      {
       "key": "editor",
       "value": "Helix"
      }
     ]
    },
    "narration": "Your program writes the row to memory.db next to this script, then appends that result to this run's list."
   },
   {
    "node": "think",
    "author": "system",
    "label": "New run",
    "text": "This is a new message list. Use recall(key) with the same short snake_case keys, like editor.",
    "codeLine": 30,
    "collapse": true,
    "set": {
     "session": 2,
     "query": null
    },
    "narration": "The next run_agent call starts a new, empty list. memory.db still has the row. The system message still names the key."
   },
   {
    "node": "think",
    "author": "user",
    "label": "User",
    "text": "Which editor do I use?",
    "codeLine": 31,
    "narration": "The question is in this new list. The answer is not, unless the model calls recall with the same key."
   },
   {
    "node": "act",
    "author": "model",
    "label": "Tool call",
    "text": "recall {\"key\": \"editor\"}",
    "codeLine": 14,
    "set": {
     "query": "editor"
    },
    "narration": "The model returns a recall tool call for the editor key, the name the system message gave it."
   },
   {
    "node": "observe",
    "author": "tool",
    "label": "Tool result",
    "text": "Helix",
    "codeLine": 16,
    "narration": "recall returns Helix, or 'no memory found for that key' if the key never matched. Append that to this run's list so the next model call can read it."
   },
   {
    "node": "think",
    "author": "model",
    "label": "Assistant",
    "text": "You use Helix.",
    "codeLine": 30,
    "narration": "The model answers from that tool result, not from the previous conversation, which this list does not contain."
   }
  ]
 },
 "ch8": {
  "id": "ch8",
  "title": "Multi-agent",
  "code": "multi_agent",
  "world": {
   "scene": "multiagent",
   "agents": [
    {
     "name": "parent",
     "role": "one tool: delegate",
     "status": "ready"
    },
    {
     "name": "researcher",
     "role": "own messages",
     "status": "idle"
    },
    {
     "name": "coder",
     "role": "own messages",
     "status": "idle"
    }
   ],
   "events": []
  },
  "intro": "A second agent is a tool. delegate runs another run_agent with its own messages. The parent list only receives the string that tool returns.",
  "steps": [
   {
    "node": "think",
    "author": "system",
    "label": "System",
    "text": "Delegate research and coding. Then answer.",
    "codeLine": 21,
    "set": {
     "agents": [
      {
       "name": "parent",
       "role": "one tool: delegate",
       "status": "running"
      },
      {
       "name": "researcher",
       "role": "own messages",
       "status": "idle"
      },
      {
       "name": "coder",
       "role": "own messages",
       "status": "idle"
      }
     ]
    },
    "narration": "The parent loop has one tool, delegate. Calling it starts a child agent."
   },
   {
    "node": "think",
    "author": "user",
    "label": "User",
    "text": "Compare Atlas and Beacon. Plan the switch.",
    "codeLine": 25,
    "narration": "The user wants a comparison and a plan. Those are two jobs, so the parent can call delegate twice."
   },
   {
    "node": "act",
    "author": "model",
    "label": "Tool call",
    "text": "delegate {\"name\": \"researcher\", \"task\": \"Compare Atlas and Beacon.\"}",
    "codeLine": 15,
    "set": {
     "agents": [
      {
       "name": "parent",
       "role": "one tool: delegate",
       "status": "waiting"
      },
      {
       "name": "researcher",
       "role": "own messages",
       "status": "running"
      },
      {
       "name": "coder",
       "role": "own messages",
       "status": "idle"
      }
     ]
    },
    "add": {
     "events": [
      "parent -> researcher: Compare Atlas and Beacon."
     ]
    },
    "narration": "delegate starts researcher. That child has its own empty message list. The parent waits."
   },
   {
    "node": "observe",
    "author": "tool",
    "label": "Tool result",
    "text": "Beacon has the smaller API and supports the required region.",
    "codeLine": 8,
    "set": {
     "agents": [
      {
       "name": "parent",
       "role": "one tool: delegate",
       "status": "running"
      },
      {
       "name": "researcher",
       "role": "own messages",
       "status": "done"
      },
      {
       "name": "coder",
       "role": "own messages",
       "status": "idle"
      }
     ]
    },
    "add": {
     "events": [
      "researcher returned one conclusion"
     ]
    },
    "narration": "The child loop finished. Only its return string is appended to the parent list. The child's messages stay private."
   },
   {
    "node": "act",
    "author": "model",
    "label": "Tool call",
    "text": "delegate {\"name\": \"coder\", \"task\": \"Plan the switch to Beacon.\"}",
    "codeLine": 15,
    "set": {
     "agents": [
      {
       "name": "parent",
       "role": "one tool: delegate",
       "status": "waiting"
      },
      {
       "name": "researcher",
       "role": "own messages",
       "status": "done"
      },
      {
       "name": "coder",
       "role": "own messages",
       "status": "running"
      }
     ]
    },
    "add": {
     "events": [
      "parent -> coder: Plan the switch to Beacon."
     ]
    },
    "narration": "The parent calls delegate again, this time for coder. That child also starts with an empty list."
   },
   {
    "node": "observe",
    "author": "tool",
    "label": "Tool result",
    "text": "Pin beacon>=2.1 and remove atlas from requirements.",
    "codeLine": 11,
    "set": {
     "agents": [
      {
       "name": "parent",
       "role": "one tool: delegate",
       "status": "running"
      },
      {
       "name": "researcher",
       "role": "own messages",
       "status": "done"
      },
      {
       "name": "coder",
       "role": "own messages",
       "status": "done"
      }
     ]
    },
    "add": {
     "events": [
      "coder returned one change"
     ]
    },
    "narration": "The coder's messages stay private. The parent list gets one more string."
   },
   {
    "node": "think",
    "author": "model",
    "label": "Assistant",
    "text": "Switch to Beacon. Pin beacon>=2.1 and drop Atlas.",
    "codeLine": 24,
    "set": {
     "agents": [
      {
       "name": "parent",
       "role": "one tool: delegate",
       "status": "done"
      },
      {
       "name": "researcher",
       "role": "own messages",
       "status": "done"
      },
      {
       "name": "coder",
       "role": "own messages",
       "status": "done"
      }
     ]
    },
    "narration": "The parent answers from those two tool results. It never received the child message lists."
   }
  ]
 },
 "loop": {
  "id": "loop",
  "title": "The agent loop",
  "code": "agent_loop",
  "world": {
   "scene": "files",
   "files": [
    {
     "name": "app.py",
     "status": ""
    },
    {
     "name": "test_app.py",
     "status": ""
    }
   ],
   "term": []
  },
  "intro": "An agent is that same model call, repeated. After your program runs a tool, it appends the result to messages and calls the model again. The loop stops when the model returns text instead of a tool call.",
  "steps": [
   {
    "node": "think",
    "author": "system",
    "label": "System",
    "text": "You are a coding agent. Tools: read_file, edit_file, run_command. Read files before answering about their contents.",
    "codeLine": 13,
    "narration": "The system message lists three tools the model may request: read_file, edit_file, and run_command."
   },
   {
    "node": "think",
    "author": "user",
    "label": "User",
    "text": "The test for add fails. Fix it.",
    "codeLine": 14,
    "narration": "The user says a test is failing. The files are not in the message list, so the model cannot see their contents yet."
   },
   {
    "node": "act",
    "author": "model",
    "label": "Tool call",
    "text": "read_file {\"path\": \"test_app.py\"}",
    "codeLine": 20,
    "set": {
     "files": [
      {
       "name": "app.py",
       "status": ""
      },
      {
       "name": "test_app.py",
       "status": "read"
      }
     ]
    },
    "add": {
     "term": [
      "$ read_file test_app.py"
     ]
    },
    "narration": "The model returns a tool call for read_file on test_app.py. Your program will run that function."
   },
   {
    "node": "observe",
    "author": "tool",
    "label": "Tool result",
    "text": "def test_add():\n    assert add(2, 2) == 5",
    "codeLine": 29,
    "add": {
     "term": [
      "3 lines"
     ]
    },
    "narration": "Your program reads the file and appends the contents to messages. Then it calls the model again with the updated list."
   },
   {
    "node": "act",
    "author": "model",
    "label": "Tool call",
    "text": "read_file {\"path\": \"app.py\"}",
    "codeLine": 20,
    "set": {
     "files": [
      {
       "name": "app.py",
       "status": "read"
      },
      {
       "name": "test_app.py",
       "status": "read"
      }
     ]
    },
    "add": {
     "term": [
      "$ read_file app.py"
     ]
    },
    "narration": "The model now has the test. It asks to read app.py."
   },
   {
    "node": "observe",
    "author": "tool",
    "label": "Tool result",
    "text": "def add(a, b):\n    return a + b",
    "codeLine": 29,
    "add": {
     "term": [
      "2 lines"
     ]
    },
    "narration": "add(2, 2) returns 4. The test asserts 5. That mismatch is now in the message list."
   },
   {
    "node": "act",
    "author": "model",
    "label": "Tool call",
    "text": "edit_file {\"path\": \"test_app.py\", \"old\": \"== 5\", \"new\": \"== 4\"}",
    "codeLine": 20,
    "add": {
     "term": [
      "$ edit_file test_app.py"
     ]
    },
    "narration": "The model asks edit_file to change the expected value from 5 to 4."
   },
   {
    "node": "observe",
    "author": "tool",
    "label": "Tool result",
    "text": "test_app.py updated",
    "codeLine": 29,
    "set": {
     "files": [
      {
       "name": "app.py",
       "status": "read"
      },
      {
       "name": "test_app.py",
       "status": "modified"
      }
     ]
    },
    "add": {
     "term": [
      "test_app.py updated"
     ]
    },
    "narration": "The edit ran. Append that observation and call the model again."
   },
   {
    "node": "act",
    "author": "model",
    "label": "Tool call",
    "text": "run_command {\"command\": \"pytest -q\"}",
    "codeLine": 20,
    "add": {
     "term": [
      "$ pytest -q"
     ]
    },
    "narration": "The model asks to run pytest."
   },
   {
    "node": "observe",
    "author": "tool",
    "label": "Tool result",
    "text": "1 passed in 0.03s",
    "codeLine": 29,
    "add": {
     "term": [
      {
       "t": "1 passed in 0.03s",
       "cls": "ok"
      }
     ]
    },
    "narration": "pytest passed. Append that result and call the model again."
   },
   {
    "node": "think",
    "author": "model",
    "label": "Assistant",
    "text": "The implementation returns the correct sum. I changed the test to expect 4 from add(2, 2), and the test passes.",
    "codeLine": 23,
    "narration": "This reply has no tool_calls. The loop returns the text and stops."
   }
  ]
 }
};
